### ISSUE TITLE
Add notebooks validation for bioimage.io manifest.yaml

### ISSUE THREAD

**Issue by m-novikov** [bioimage-io/python-bioimage-io#45]
Related: #44 
```
Traceback (most recent call last):
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work/projects/ilastik-project/tiktorch/vendor/python-bioimage-io/pybio/spec/__main__.py", line 75, in <module>
    app()
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/work/projects/ilastik-project/tiktorch/vendor/python-bioimage-io/pybio/spec/__main__.py", line 69, in verify_bioimageio_manifest
    code = verify_bioimageio_manifest_data(manifest_data)
  File "/home/work/projects/ilastik-project/tiktorch/vendor/python-bioimage-io/pybio/spec/__main__.py", line 40, in verify_bioimageio_manifest_data
    manifest = schema.BioImageIoManifest().load(manifest_data)
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/work/tools/miniconda3/envs/tiktorch-server-env/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'notebook': {0: {'documentation': ['Unknown field.']}}}
```

**Comment by m-novikov** [comment]
Extra field documentation is added in latest master
