### ISSUE TITLE
KeyError: 'tensorflow_saved_model_bundle'

### ISSUE THREAD

**Issue by oeway** [bioimage-io/python-bioimage-io#50]
Running the verification script in the CI and I got this error: 
(https://github.com/deepimagej/models/runs/1963020995)
```
Traceback (most recent call last):
  File "compile_model_manifest.py", line 270, in <module>
    parse_manifest(models_yaml)
  File "compile_model_manifest.py", line 200, in parse_manifest
    spec.verify_model_data(model_config)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pybio/spec/__main__.py", line 36, in verify_model_data
    schema.Model().load(model_data)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/marshmallow/schema.py", line 886, in _do_load
    field_errors=field_errors,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/marshmallow/schema.py", line 1191, in _invoke_schema_validators
    partial=partial,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/marshmallow/schema.py", line 774, in _run_validator
    validator_func(output, partial=partial, many=many)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pybio/spec/schema.py", line 324, in source_specified_if_required
    require_source = {wf for wf in data["weights"] if weight_format_requires_source[wf]}
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pybio/spec/schema.py", line 324, in <setcomp>
    require_source = {wf for wf in data["weights"] if weight_format_requires_source[wf]}
KeyError: 'tensorflow_saved_model_bundle'
```

**Comment by FynnBe** [comment]
fixed in b68184a09f673b2bc0aa9c19e2df00ea4e63546d
